apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: smartdevops-alerts
  namespace: monitoring
  labels:
    release: kps     # â† Ù…Ù‡Ù… Ø¬Ø¯Ø§Ù‹ØŒ ÙŠØ·Ø§Ø¨Ù‚ Helm release name
spec:
  groups:
    - name: smartdevops-alerts
      rules:

        # ðŸ”´ Pod Failed
        - alert: PodDown
          expr: kube_pod_status_phase{phase="Failed"} > 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "âŒ A Pod has crashed"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in a Failed state for more than 2 minutes."

        # ðŸŸ¡ Pod Pending Too Long
        - alert: PodPendingTooLong
          expr: kube_pod_status_phase{phase="Pending"} > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "âš ï¸ Pod stuck in Pending"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been Pending for more than 5 minutes."

        # ðŸ”¥ High CPU Usage (by namespace)
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace!=\"\"}[5m])) by (namespace) > 0.8
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "ðŸ”¥ High CPU usage detected"
            description: "Namespace {{ $labels.namespace }} is using more than 80% CPU for over 3 minutes."

        # ðŸ’¥ High Memory Usage (namespace memory vs limits)
        - alert: HighMemoryUsage
          expr: |
            sum(container_memory_usage_bytes{container!=""}) by (namespace)
            /
            sum(kube_pod_container_resource_limits_memory_bytes{container!=""}) by (namespace)
            > 0.9
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "ðŸ’¥ High memory usage detected"
            description: "Namespace {{ $labels.namespace }} is using more than 90% of its memory limit."
