apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-api
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]

  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get","list","watch"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-api
  namespace: default
subjects:
  - kind: ServiceAccount
    name: platform-api
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-api
