apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-api-deployer
  namespace: <TENANT_NS>
subjects:
  - kind: ServiceAccount
    name: platform-api
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-deployer

