apiVersion: v1
kind: Service
metadata:
  name: platform-api
  namespace: default
  labels:
    app: platform-api
    managed-by: cloud-devops-platform
spec:
  type: ClusterIP
  selector:
    app: platform-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
