

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smartdevops-tls-prod
  namespace: default
spec:
  secretName: smartdevops-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: smartdevops.lat
  dnsNames:
    - smartdevops.lat
