
apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/k8s/platform-db
    type: DirectoryOrCreate
